### ISSUE TITLE
Permission to elielnfinic/unimage.git denied to NdekoCode.

### ISSUE THREAD

**Issue by NdekoCode** [elielnfinic/unimage#2]
Je ne peut pas envoyer les modifications sur la branche sur le repos, j'ai l'erreur suivante: 
`fatal: unable to access 'https://github.com/elielnfinic/unimage.git/': The requested URL returned error: 403`

**Comment by elielnfinic** [comment]
Pouvez-vous envoyer les modifications sur une autre branche?

**Comment by NdekoCode** [comment]
C'est déjà, j'ai viens de faire un pull request sur la branche `develop`

**Comment by NdekoCode** [comment]
C'etais quoi la suite ?
